[mypy]
python_version = 3.11
ignore_missing_imports = False

[mypy-langgraph.*]
ignore_missing_imports = True

[mypy-langchain_core.*]
ignore_missing_imports = True

[mypy-piexif.*]
ignore_missing_imports = True

[mypy-PIL.*]
ignore_missing_imports = True

[mypy-obsws_python.*]
ignore_missing_imports = True
